DROP TABLE IF EXISTS TB_USER;

CREATE TABLE TB_USER(
    USERNAME varchar2(20) PRIMARY KEY,
    PASSWORD VARCHAR2(100) NOT NULL
);


INSERT INTO TB_USER (USERNAME, PASSWORD) VALUES
    ('TESTE 1','123'),
    ('TESTE 2','456');